import { FlightPhase } from '../../types/flightPhase'
import type { TelemetryProfile } from '../../types/telemetry'

export const TELEMETRY_PROFILES: Record<FlightPhase, TelemetryProfile> = {
  [FlightPhase.PREFLIGHT]: {
    phase: FlightPhase.PREFLIGHT,
    durationSeconds: 30,
    altitude: { target: 0, variance: 0, rampRate: 100 },
    indicatedAirspeed: { target: 0, variance: 0, rampRate: 10 },
    verticalSpeed: { target: 0, variance: 0, rampRate: 50 },
    heading: { target: 145, variance: 0, rampRate: 1 },
    pitch: { target: 0, variance: 0, rampRate: 0.5 },
    roll: { target: 0, variance: 0, rampRate: 0.5 },
    gForce: { target: 1.0, variance: 0, rampRate: 0.1 },
    n1: { target: 0, variance: 0, rampRate: 2 },
    n2: { target: 0, variance: 0, rampRate: 2 },
    egt: { target: 15, variance: 2, rampRate: 5 },
    fuelBurnRate: { target: 0, variance: 0, rampRate: 10 },
    hydraulicsPressure: { target: 0, variance: 0, rampRate: 10 },
    anomalyProbabilityPerSecond: 0,
  },
  [FlightPhase.STARTUP]: {
    phase: FlightPhase.STARTUP,
    durationSeconds: 25,
    altitude: { target: 0, variance: 0, rampRate: 10 },
    indicatedAirspeed: { target: 0, variance: 0, rampRate: 5 },
    verticalSpeed: { target: 0, variance: 0, rampRate: 10 },
    heading: { target: 145, variance: 0, rampRate: 1 },
    pitch: { target: 0, variance: 0.2, rampRate: 0.5 },
    roll: { target: 0, variance: 0.1, rampRate: 0.5 },
    gForce: { target: 1.0, variance: 0, rampRate: 0.1 },
    n1: { target: 18, variance: 1, rampRate: 5 },
    n2: { target: 20, variance: 1, rampRate: 5 },
    egt: { target: 480, variance: 15, rampRate: 40 },
    fuelBurnRate: { target: 800, variance: 50, rampRate: 100 },
    hydraulicsPressure: { target: 3000, variance: 50, rampRate: 200 },
    anomalyProbabilityPerSecond: 0.002,
  },
  [FlightPhase.TAXI]: {
    phase: FlightPhase.TAXI,
    durationSeconds: 30,
    altitude: { target: 0, variance: 0, rampRate: 10 },
    indicatedAirspeed: { target: 20, variance: 5, rampRate: 5 },
    verticalSpeed: { target: 0, variance: 0, rampRate: 5 },
    heading: { target: 180, variance: 10, rampRate: 3 },
    pitch: { target: 0, variance: 0.5, rampRate: 0.5 },
    roll: { target: 0, variance: 1, rampRate: 1 },
    gForce: { target: 1.0, variance: 0.05, rampRate: 0.1 },
    n1: { target: 25, variance: 2, rampRate: 3 },
    n2: { target: 27, variance: 2, rampRate: 3 },
    egt: { target: 520, variance: 10, rampRate: 10 },
    fuelBurnRate: { target: 1200, variance: 100, rampRate: 50 },
    hydraulicsPressure: { target: 3000, variance: 30, rampRate: 100 },
    anomalyProbabilityPerSecond: 0.003,
  },
  [FlightPhase.TAKEOFF]: {
    phase: FlightPhase.TAKEOFF,
    durationSeconds: 25,
    altitude: { target: 1500, variance: 50, rampRate: 60 },
    indicatedAirspeed: { target: 160, variance: 5, rampRate: 8 },
    verticalSpeed: { target: 2500, variance: 200, rampRate: 200 },
    heading: { target: 175, variance: 2, rampRate: 2 },
    pitch: { target: 12, variance: 1, rampRate: 2 },
    roll: { target: 0, variance: 2, rampRate: 1 },
    gForce: { target: 1.35, variance: 0.1, rampRate: 0.2 },
    n1: { target: 95, variance: 1, rampRate: 10 },
    n2: { target: 97, variance: 1, rampRate: 10 },
    egt: { target: 890, variance: 20, rampRate: 30 },
    fuelBurnRate: { target: 8500, variance: 300, rampRate: 500 },
    hydraulicsPressure: { target: 3000, variance: 50, rampRate: 100 },
    anomalyProbabilityPerSecond: 0.008,
  },
  [FlightPhase.CLIMB]: {
    phase: FlightPhase.CLIMB,
    durationSeconds: 40,
    altitude: { target: 35000, variance: 200, rampRate: 800 },
    indicatedAirspeed: { target: 280, variance: 8, rampRate: 5 },
    verticalSpeed: { target: 1800, variance: 200, rampRate: 100 },
    heading: { target: 175, variance: 3, rampRate: 1 },
    pitch: { target: 8, variance: 1, rampRate: 1 },
    roll: { target: 0, variance: 1.5, rampRate: 0.5 },
    gForce: { target: 1.1, variance: 0.08, rampRate: 0.1 },
    n1: { target: 88, variance: 2, rampRate: 5 },
    n2: { target: 90, variance: 2, rampRate: 5 },
    egt: { target: 820, variance: 15, rampRate: 20 },
    fuelBurnRate: { target: 6800, variance: 200, rampRate: 300 },
    hydraulicsPressure: { target: 3000, variance: 30, rampRate: 50 },
    anomalyProbabilityPerSecond: 0.004,
  },
  [FlightPhase.CRUISE]: {
    phase: FlightPhase.CRUISE,
    durationSeconds: 50,
    altitude: { target: 35000, variance: 100, rampRate: 200 },
    indicatedAirspeed: { target: 450, variance: 10, rampRate: 3 },
    verticalSpeed: { target: 0, variance: 100, rampRate: 50 },
    heading: { target: 175, variance: 2, rampRate: 0.5 },
    pitch: { target: 2, variance: 0.5, rampRate: 0.5 },
    roll: { target: 0, variance: 1, rampRate: 0.3 },
    gForce: { target: 1.0, variance: 0.05, rampRate: 0.05 },
    n1: { target: 82, variance: 1, rampRate: 2 },
    n2: { target: 84, variance: 1, rampRate: 2 },
    egt: { target: 760, variance: 10, rampRate: 10 },
    fuelBurnRate: { target: 5200, variance: 150, rampRate: 100 },
    hydraulicsPressure: { target: 3000, variance: 20, rampRate: 30 },
    anomalyProbabilityPerSecond: 0.002,
  },
  [FlightPhase.DESCENT]: {
    phase: FlightPhase.DESCENT,
    durationSeconds: 40,
    altitude: { target: 2000, variance: 200, rampRate: 800 },
    indicatedAirspeed: { target: 250, variance: 10, rampRate: 5 },
    verticalSpeed: { target: -1500, variance: 200, rampRate: 150 },
    heading: { target: 175, variance: 3, rampRate: 1 },
    pitch: { target: -3, variance: 1, rampRate: 0.8 },
    roll: { target: 0, variance: 1.5, rampRate: 0.5 },
    gForce: { target: 1.0, variance: 0.08, rampRate: 0.1 },
    n1: { target: 40, variance: 3, rampRate: 8 },
    n2: { target: 42, variance: 3, rampRate: 8 },
    egt: { target: 580, variance: 20, rampRate: 30 },
    fuelBurnRate: { target: 2200, variance: 150, rampRate: 200 },
    hydraulicsPressure: { target: 3000, variance: 30, rampRate: 50 },
    anomalyProbabilityPerSecond: 0.005,
  },
  [FlightPhase.LANDING]: {
    phase: FlightPhase.LANDING,
    durationSeconds: 30,
    altitude: { target: 0, variance: 0, rampRate: 100 },
    indicatedAirspeed: { target: 0, variance: 0, rampRate: 10 },
    verticalSpeed: { target: -700, variance: 50, rampRate: 100 },
    heading: { target: 175, variance: 1, rampRate: 2 },
    pitch: { target: 3, variance: 0.5, rampRate: 0.5 },
    roll: { target: 0, variance: 0.5, rampRate: 0.5 },
    gForce: { target: 1.2, variance: 0.1, rampRate: 0.2 },
    n1: { target: 22, variance: 2, rampRate: 5 },
    n2: { target: 24, variance: 2, rampRate: 5 },
    egt: { target: 500, variance: 15, rampRate: 20 },
    fuelBurnRate: { target: 1000, variance: 100, rampRate: 100 },
    hydraulicsPressure: { target: 3000, variance: 50, rampRate: 100 },
    anomalyProbabilityPerSecond: 0.006,
  },
}
